name: Auto Release

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

permissions:
  contents: write # Grant permission to create a release

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # Retrieve the latest tag or set to v0.0.0 if no tags exist
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Set new version
        id: set_version
        run: |
          # Define your new starting version
          new_start_version="v0.0.0"
          latest_tag="${{ steps.get_latest_tag.outputs.latest_tag }}"
          # Check if the latest tag is less than the new starting version
          if [ "$(printf '%s\n' "$latest_tag" "$new_start_version" | sort -V | head -n1)" != "$new_start_version" ]; then
            echo "new_version=$new_start_version" >> $GITHUB_OUTPUT
          else
            # Increment version if latest tag is not less than the new start version
            version="${latest_tag#v}"  # Remove the 'v' prefix
            IFS='.' read -r major minor patch <<< "$version"
            new_patch=$((patch + 1))
            new_version="v$major.$minor.$new_patch"
            echo "new_version=$new_version" >> $GITHUB_OUTPUT
          fi

      - name: Create a new release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN from environment
        with:
          tag_name: ${{ steps.set_version.outputs.new_version }}
          release_name: "Release ${{ steps.set_version.outputs.new_version }}"
          draft: false
          prerelease: false
